name: Scan images
on:
  pull_request:
    paths:
      - 'services/localega-tsd-proxy/**'
      - 'services/mq-interceptor/**'
    branches:
      - main
    types:
      - closed
jobs:
  detect-changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      localega-tsd-proxy: ${{ steps.changes.outputs.localega-tsd-proxy }}
      mq-interceptor: ${{ steps.changes.outputs.mq-interceptor }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            localega-tsd-proxy:
              - 'services/localega-tsd-proxy/**'
            mq-interceptor:
              - 'services/mq-interceptor/**'
  
  

  localega_tsd_proxy:
    needs: detect-changes
    if: needs.detect-changes.outputs.localega-tsd-proxy == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Set Repository Name
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/${{ env.repo_name }}:localega-tsd-proxy-${{ github.event.number }}
          format: 'sarif'
          severity: "CRITICAL,HIGH,MEDIUM"
          ignore-unfixed: true
          output: 'tsd-proxy-result.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'tsd-proxy-result.sarif'
          category: 'tsd-proxy'
  mq-interceptor:
    needs: detect-changes
    if: needs.detect-changes.outputs.mq-interceptor == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
    steps:
      - name: Set Repository Name
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/${{ env.repo_name }}:mq-interceptor-${{ github.event.number }}
          format: 'sarif'
          ignore-unfixed: true
          output: 'mq-interceptor-result.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'mq-interceptor-result.sarif'
          category: 'mq-interceptor'
